Stormguard

diff --git a/update-binary b/update-binary
--- a/update-binary
+++ b/update-binary
@@ -3,8 +3,8 @@
 # osm0sis @ xda-developers
 
 OUTFD=/proc/self/fd/$2;
-ZIP="$3";
-DIR=`dirname "$ZIP"`;
+ZIPFILE="$3";
+DIR=`dirname "$ZIPFILE"`;
 
 ui_print() {
   until [ ! "$1" ]; do
@@ -13,65 +13,85 @@ ui_print() {
   done;
 }
 show_progress() { echo "progress $1 $2" > $OUTFD; }
-set_perm_recursive() {
-  dirs=$(echo $* | $bb awk '{ print substr($0, index($0,$5)) }');
-  for i in $dirs; do
-    $bb chown -R $1:$2 $i;
-    find "$i" -type d -exec chmod $3 {} +;
-    find "$i" -type f -exec chmod $4 {} +;
-  done;
-}
-file_getprop() { grep "^$2" "$1" | cut -d= -f2; }
-getprop() { test -e /sbin/getprop && /sbin/getprop $1 || file_getprop /default.prop $1; }
-cleanup() { rm -rf /tmp/anykernel; }
-if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.cleanuponabort)" == 1 ]; then
-    abort() { ui_print "$*"; cleanup; umount /system; umount /data; exit 1; }
-  else
-    abort() { ui_print "$*"; umount /system; umount /data; exit 1; }
+file_getprop() { grep "^$2=" "$1" | cut -d= -f2; }
+if [ ! "$(getprop 2>/dev/null)" ]; then
+  getprop() {
+    local propval="$(file_getprop /default.prop $1 2>/dev/null)";
+    test "$propval" || local propval="$(file_getprop /system/build.prop $1 2>/dev/null)";
+    test "$propval" && echo "$propval" || echo "";
+  }
 fi;
+cleanup() { rm -rf /tmp/anykernel; }
+debugging() {
+  case $(basename "$ZIPFILE" .zip) in
+    *-debugging)
+      ui_print " ";
+      ui_print " - Creating debugging archive in zip directory...";
+      $bb tar -czvf "$DIR/anykernel2-$(date +%Y-%m-%d_%H%M%S)-debug.tgz" /tmp/*;
+    ;;
+  esac;
+}
+abort() {
+  ui_print "$*";
+  debugging;
+  if [ ! -f /tmp/anykernel/anykernel.sh -o "$(file_getprop /tmp/anykernel/anykernel.sh do.cleanuponabort 2>/dev/null)" == 1 ]; then
+    cleanup;
+  fi;
+  umount /system;
+  umount /data 2>/dev/null;
+  exit 1;
+}
 
 show_progress 1.34 4;
 ui_print " ";
 cleanup;
 mkdir -p /tmp/anykernel/bin;
 cd /tmp/anykernel;
-unzip -o "$ZIP";
+unzip -o "$ZIPFILE";
 if [ $? != 0 -o -z "$(ls /tmp/anykernel/tools)" ]; then
-  abort "Unzip failed. Aborting...";
+  abort " ! Unzip failed. Aborting...";
 fi;
-chmod -R 755 /tmp/anykernel/tools /tmp/anykernel/bin;
 bb=/tmp/anykernel/tools/busybox;
+chmod 755 $bb;
+$bb chmod -R 755 /tmp/anykernel/tools /tmp/anykernel/bin;
 
 ui_print "$(file_getprop /tmp/anykernel/anykernel.sh kernel.string)";
 ui_print " ";
-ui_print "Soviet Kernel For Redmi Note 4";
+ui_print "        ____       ____ ";
+ui_print "       / ___|     / ___|";
+ui_print "       \___ \    | |  _ ";
+ui_print "        ___) v4.2| |_| |";
+ui_print "       |____/torm \____|uard";
 ui_print " ";
-umount /system;
+ui_print "AnyKernel2 by osm0sis @ xda-developers";
+ui_print " ";
+umount /system 2>/dev/null;
 mount -o ro -t auto /system;
-mount /data;
+mount -o ro -t auto /vendor 2>/dev/null;
+mount /data 2>/dev/null;
 test -f /system/system/build.prop && root=/system;
 
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.devicecheck)" == 1 ]; then
-  ui_print "Checking device...";
+  ui_print " - Checking device...";
   for i in 1 2 3 4 5; do
     testname="$(file_getprop /tmp/anykernel/anykernel.sh device.name$i)";
     if [ "$(getprop ro.product.device)" == "$testname" -o "$(getprop ro.build.product)" == "$testname" ]; then
-      ui_print "$testname";
+      ui_print "   Device supported [$testname].";
       match=1;
     fi;
   done;
   ui_print " ";
   if [ "$match" != 1 ]; then
-    abort "Unsupported device. Aborting...";
+    abort " ! Unsupported device. Aborting...";
   fi;
 fi;
 
-ui_print "Installing kernel...";
+ui_print " - Installing kernel...";
 for i in $($bb --list); do
   $bb ln -s $bb /tmp/anykernel/bin/$i;
 done;
 if [ $? != 0 -o -z "$(ls /tmp/anykernel/bin)" ]; then
-  abort "Recovery busybox setup failed. Aborting...";
+  abort " ! Recovery busybox setup failed. Aborting...";
 fi;
 PATH="/tmp/anykernel/bin:$PATH" $bb ash /tmp/anykernel/anykernel.sh $2;
 if [ $? != "0" ]; then
@@ -80,18 +100,36 @@ fi;
 
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.modules)" == 1 ]; then
   ui_print " ";
-  ui_print "Pushing modules...";
+  ui_print " - Pushing modules...";
   mount -o rw,remount -t auto /system;
-  cp -rf /tmp/anykernel/modules/* $root/system/lib/modules/;
-  set_perm_recursive 0 0 0755 0644 $root/system/lib/modules;
+  mount -o rw,remount -t auto /vendor 2>/dev/null;
+  cd /tmp/anykernel/modules;
+  for module in $(find . -name '*.ko'); do
+    if [ ! -e /$module ]; then
+      case $module in
+        */vendor/*) mod=vendor;;
+        *) mod=system;;
+      esac;
+    fi;
+    $bb cp -rLf $module /$module;
+    $bb chown 0:0 /$module;
+    $bb chmod 644 /$module;
+    if [ "$mod" ]; then
+      chcon "u:object_r:${mod}_file:s0" /$module;
+    fi;
+  done;
+  cd /tmp/anykernel;
   mount -o ro,remount -t auto /system;
+  mount -o ro,remount -t auto /vendor 2>/dev/null;
 fi;
+
+debugging;
 
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.cleanup)" == 1 ]; then
   cleanup;
 fi;
 
 umount /system;
-umount /data;
+umount /data 2>/dev/null;
 ui_print " ";
-ui_print "Done!";
+ui_print " - Done!";
